<?php

namespace app\Http\Controllers\Bbva;

use Log;
use Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Webpatser\Uuid\Uuid;
use App\Http\Controllers\Controller;
use App\Models\Transaccion;
//use App\Classes\Sistema\Mensaje;
use App\Classes\Pagos\Parametros\PeticionCargo;
use App\Classes\Pagos\Procesadores\Bbva\Mensaje;
use App\Classes\Pagos\Procesadores\Bbva\Interred as BBVAInterred;

require public_path('b.php');
use app\Prueba\Bbva\BbvaTest;


class BbvaController extends Controller
{

    /**
     * Crea nueva instancia.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $oRequest)
    {
        $sPrueba = $oRequest->input('prueba', '1');
        $sTipo = $oRequest->input('tipo', 'envio_online');
        $sAccion = $oRequest->input('accion', 'prueba');
        $sTrxReq = base64_decode(urldecode($oRequest->input('trx_request', null)));
        $sTrxResp = base64_decode(urldecode($oRequest->input('trx_response', null)));
        // Prepara prueba
        $oBbvaTest = new BbvaTest();
        try {
            $oResultado = $oBbvaTest->pruebas($sPrueba, $sTipo, $sAccion, $sTrxReq, $sTrxResp);
        } catch (\Exception $e) {
            $iCode = $e->getCode();
            if (empty($iCode)) {
                $iCode = 520;
            }
            return ejsend_error(['code' => $iCode, 'type' => 'Sistema', 'message' => $e->getMessage() . ' ' . $e->getLine()], $iCode);
        }

        if (in_array($sTipo, ['datos_json', 'envio_json'])) {
            // Obtiene los datos a enviar de la prueba
            return ejsend_success($oResultado);
        } else if ($sTipo == 'envio_online') {
            echo "\n<br>Ejecutando prueba {$sPrueba}...";
            return $oResultado;
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $oRequest)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, int $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        //
    }



    public function batch()
    {
        $i = 1;
        $fecha = '2018-05-11';
        $dFecha = strtotime($fecha);
        $fecha_ymd = date('ymd', $dFecha);

        $sFechaProc = strtotime("+1 day", $dFecha);
        $fecha_proc_ymd = date('ymd', $sFechaProc);
        $batch_filename = 'rmd1' . date('dmy', $sFechaProc) . '.txt';

        $batch_header_1 = [

            sprintf("%06s", $i++), // [6] Número de registro
            '1', // [1] Tipo de registro. Fijo: 1
            'EGLO', // [4] Número de sistema. Fijo: EGLO
            $fecha_proc_ymd, // [6] Fecha de transmisión (AAMMDD)
            'STS     ', // [8] Nombre de la cadena (convenido con BBVA Bancomer)
            '01', // [2] Número NN fijo. Número asignado por BBVA Bancomer a la Interred
            '01', // [2] Número de ventana que corresponde en el día
            '01.30', // [5] Versión del Formato del archivo. Fijo: 01.30
            substr($batch_filename, 0, 8), // [8] Nombre físico del presente archivo
            '00', // [2] Sentido del archivo: 00 = viaja de la Interred hacia BBVA Bancomer 01 = viaja de BBVA Bancomer hacia la Interred
            '                                                                             ', // [77] Espacios para uso futuro
        ];
        $batch_header_2 = [
            sprintf("%06s", $i++), // [6] Número consecutivo de registro
            '2', // [1] Tipo de registro. Fijo: 2
            '05462742', // [8] Identificador propio del Negocio por parte de la Interred
            '05462742', // [8] Número que BBVA Bancomer otorga al negocio para su identificación
            '00000000', // [8] Número de referencia a la cuenta de cheques. Es opcional y solo informativo
            '000', // [3] Número de la sucursal (opcional y solo informativo)
            '0000000', // [7] Número de la cuenta de cheques  (opcional y solo es informativo
            '00000000', // [8] Número de referencia de cargos parciales
            '                                                                        ', // [72] Espacios para uso futuro
        ];


        $batch_line = [
            '000003', // [6] Número consecutivo de registro
            '3', // [1] Tipo de registro. Fijo 3
            '161019', // [6] Fecha valor del pagare (AAMMDD)
            '1', // [1] Clave de la operación del Pagaré 1= Compra On-Line (Aut.Bnmx) 2= Compra On-Line (Aut.Cadena) 3= Compra Off-Line 4= Devolución 5= Compra diferida On-Line 6= Devolución Diferida Off-Line
            '125085', // [6] Número con el cual autorizó BBVA Bancomer
            '0000011100', // [10] Monto de la transacción
            // [23] Número único para la localización de pagares “
                '7455546', // [7] 7455546” = Valor Fijo.
                '6', // [1] “A” = último dígito del año.
                '293', // [3] “DDD = fecha juliana.
                '00600300023', // [11] “99999999999” = 11 posiciones libre numérico.
                '9', // [1]  “1” = dígito verificador ( módulo 10)
            '4772133014153321   ', // [19] Número de tarjeta (BBVA Bancomer, Visa, MC, BBVA Bancomer, Carnet, Amex)
            '0000', // [4] Motivo de rechazo del movimiento. Campo exclusivo para BBVA Bancomer. La interred debe enviar el valor fijo: 0000
            '0000', // [4] Estatus del registro. La interred debe enviar el valor fijo: 0000
            '102130', // [6] Hora en que se efectúo la transacción (HHMMSS)
            '0000', // [4] Indicador de Comercio Electrónico: 0 = No es transacción de Comercio Electrónico 5 =Transacción electrónica segura con certificado del tarjetahabiente 6 =Transacción electrónica segura sin certificado del tarjetahabiente, con certificado del negocio 7 =Transacción de comercio electrónico sin certificados, con canal encriptado 8 = Transacción de comercio electrónico No segura
            '01', // [2] Modo de ingreso de datos de la cuentas emisora: “00” Información desconocida “01” Información digitada “05” Información obtenida de tarjeta con chip. “07” Contactless “80” FallBack  “90” Información obtenida de la banda magnética del plástico “91” Contactless MSD (banda magnética)
            '000000000', // [9] Cash back 7 enteros 2 decimales
            '1', // [1] Capacidad de la terminal para lectura de datos: '1' No hay terminal (elaborado manualmente) '2' Con lectora de banda '3' Contactless  '4' Lector de caracteres ópticos '5' Lector de CHIP(circuito integrado)
            '00', // [2] Plan a utilizarse '00' Sin plan '03' Plan sin intereses '05' Plan con intereses '07' Compre hoy pague después
            '00', // [2] Número de meses en que el pago no se hace exigible(Compre hoy, pague después)
            '00', // [2] Número de meses en que se van a dividir los pagos (con o sin intereses), justificado con ceros a la izquierdo.
            '000000', // [6] Número de boleta utilizado en la transacción
            '0000', // [4] Número de terminal donde se efectuó la transacción
            '000', // [3] Número de tienda donde se efectuó la transacción
        ];

        $aTrx['180511'] = [
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDE4MzEwMDA1MTExNDMzMDkxODU5MDkwOTMzMDkwNTExMDUxMTA1MTEwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTExMDkzMzA5MDI1MDI1MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMjAwMDAwMDAwMDAyMDAwMDAwMDAwMDIwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDIwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAyMjQwMDA1MTExNDM2NDAyNDUwMzkwOTM2NDAwNTExMDUxMTA1MTEwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTExMDkzNjQwMDI1MDI4MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA1MzM1NTA1MTExNDM4MjUwNzE0NDAwOTM4MjUwNTExMDUxMTA1MTEwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTExMDkzODI1MDI1MDI5MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDA3MjkwMDA1MTExNDM5NTY0Mjk2MTIwOTM5NTYwNTExMDUxMTA1MTEwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTExMDkzOTU2MDI1MDMwMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMjAwMDAwMDAwMDAyMDAwMDAwMDAwMDIwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDIwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDAzNjEwMDA1MTExNDQ4NDc1Njc0NTkwOTQ4NDcwNTExMDUxMTA1MTEwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTExMDk0ODQ3MDI1MDMyMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDM2MTAwMDAwMDAwMzYxMDAxMDAwMDAwMTYzOTAwMDAwMDAyMDAwMDAwMDAwMDIwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDE2MzkwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDEzNjM1NTA1MTExNDUyNDA4MzcxMzMwOTUyNDAwNTExMDUxMTA1MTEwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTExMDk1MjQwMDI1MDM1MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMTM2MzUwMDAwMDAxMzYzNTAxMDAwMDAwMDI3NTUwMDAwMDAxNjM5MDAwMDAwMDE2MzkwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAyNzU1NDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA4NzMwMDA1MTExNDU0MDA2NDY1NTAwOTU0MDAwNTExMDUxMTA1MTEwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTExMDk1NDAwMDI1MDM3MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA1MDkwMDA1MTExNDU1NDY0MTEyMTYwOTU1NDYwNTExMDUxMTA1MTEwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUxMTA5NTU0NjAyNTAzOTAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAyNzU1MDAwMDAwMDI3NTUwMDAwMDAwMjc1NTAgICAgICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMjc1NTQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAwNjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA4MzU4MDA1MTExNDU5MzAxODk4NTcwOTU5MzAwNTExMDUxMTA1MTEwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUxMTA5NTkzMDAyNTA0MTAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAyNzU1MDAwMDAwMDI3NTUwMDAwMDAwMjc1NTAgICAgICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMjc1NTQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAxMjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA5MzYwMDA1MTExNTAxMzc1MzQ2MjYxMDAxMzcwNTExMDUxMTA1MTEwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUxMTEwMDEzNzAyNTA0MjAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAyNzU1MDAwMDAwMDI3NTUwMDAwMDAwMjc1NTAgICAgICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMjc1NTQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAxODAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDAyMjQwMDA1MTExNTA2MjMyNTQyMjkxMDA2MjMwNTExMDUxMTA1MTEwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTExMTAwNjIzMjExNTMxMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDEzNjM1NTA1MTExNTA3NTY3ODAxMjQxMDA3NTYwNTExMDUxMTA1MTEwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTExMTAwNzU2MjExNTMyMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDA4MzU4MDA1MTExNTA4NDYyODgxMjIxMDA4NDYwNTExMDUxMTA1MTEwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTExMTAwODQ2MjExNTMzMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAyMjg1MDA1MTExNjI0MTk2MDYyNDExMTI0MTkwNTExMDUxMTA1MTEwMTI1OTIxNTQxMzMzMDA4OTAyMDAxMT0yNTEyMTgwNTExMTEyNDE5MDA1NjYxMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA2MDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAzMDMwMDA1MTExNjI1Mjg3MzYxNjAxMTI1MjgwNTExMDUxMTA1MTEwMTI1OTIxNTQxMzMzMDA4OTAyMDA3OD0yNTEyMTgwNTExMTEyNTI4MDA1NjYyMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAxNTcwMDA1MTExNjI3MDQyNzg3NjExMTI3MDQwNTExMDUxMTA1MTEwMTI1OTIxNTQxMzMzMDA4OTAyMDA4Nj0yNTEyMTgwNTExMTEyNzA0MDA1NjYzMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDEzMDcwMDA1MTExNjI4MTEwMDE5MjUxMTI4MTEwNTExMDUxMTA1MTEwMTI1OTIxNTQxMzMzMDA4OTAxMDQ4Mz0yNTEyMTgwNTExMTEyODExMDA1NjY0MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA0NTIwMDA1MTExNjI5MjI4NTUzNzgxMTI5MjIwNTExMDUxMTA1MTEwMTI1OTIxNTQxMzMzMDA4OTAxMDQ0Mj0yNTEyMTgwNTExMTEyOTIyMDA1NjY1MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
        ];

        $aTrx['180504'] = [
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDE4MzAwMDA1MDQxNDE1Mzk0OTYxNDIwOTE1MzkwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkxNTM5OTI1MDE5MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDI3NzUwMDAwMDAwMjc3NTAwMDAwMDAyNzc1MCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAyNzc1NDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAyMjMwMDA1MDQxNDIwMzU1MzAyNzgwOTIwMzUwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MDkyMDM1OTI1MDI0MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAyMjMwMDA1MDQxNDIwMzk5ODU2MzcwOTIwMzkwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MDkyMDM5OTI1MDI1MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA1MzI1NTA1MDQxNDIzMDIyODYwOTkwOTIzMDIwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MDkyMzAyOTI1MDI2MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDA3MjgwMDA1MDQxNDI0MDU4NTE4MDcwOTI0MDUwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkyNDA1OTI1MDI5MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDI3NzUwMDAwMDAwMjc3NTAwMDAwMDAyNzc1MCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAyNzc1NDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjE4MDAwMDAwMDAwMDA0MTIwMDA1MDQxNDI1MDMxODI0MTYwOTI1MDMwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkyNTAzMDAwMDAwNDkwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBEICAgICAgICEgQzAwMDAyNiAxMjMgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAzNzg3MDA1MDQxNDI2MTMwOTg3MTYwOTI2MTMwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MDkyNjEzMDAwMDAwNDgwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAgICAgIDAwMSAgICAgICAgICA3ICA5IDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA4MTIwMDA1MDQxNDI3MTQ4NzkwNzkwOTI3MTQwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MDkyNzE0MDAwMDAwNDkwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0NTYgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjE4MDAwMDAwMDAwMDA4MzAwMDA1MDQxNDI4MTY5NjI2MTcwOTI4MTYwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkyODE2MDAwMDAwMDUwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiAgICAgIDAwMSAgICAgICAgICA3ICA5IDAgMA==',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDAzNjAwMDA1MDQxNDI5MTM1MDE5NzMwOTI5MTMwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkyOTEzOTI1MDMzMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDI3NzUwMDAwMDAwMjc3NTAxMDAwMDAwMDAwMDAwMDAwMDAwMjc3NTAwMDAwMDAyNzc1MCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDE4MzAwMDA1MDQxNDMyNDY2NzA0NjgwOTMyNDYwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkzMjQ2OTI1MDM2MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDEzNjI1NTA1MDQxNDMyNDgyMjUzNjUwOTMyNDgwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MDkzMjQ4OTI1MDM3MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA4NzIwMDA1MDQxNDM3NDAzNjkyMDUwOTM3NDAwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MDkzNzQwOTI1MDQyMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA1MDgwMDA1MDQxNDM4Mzg0NzE3NzgwOTM4MzgwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDA5MzgzODkyNTA0MzAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAwNjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AXpJU08wMjM0MDAwNzA5MjAwMzIzODg0MDEyODgxODA1MjE4MDAwMDAwMDAwMDA4MzQ4MDA1MDQxNDU3Mzg2NTcwNjQwOTU3MzgwNTA0MDUwNDAxMjAyMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDA5NTczODAwMDBDUDAxICAgICAgICAwMjc1NDYyNzQyICAgICAgICAgICAgMDAwMDAwMDA0ODQwNDAyMDIwMjAyMDIwMjAyMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE2Q0xQR1RFUzErMDAwMDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDEyMDMhIDA0MDAwMjAgICAgICAgICAgICAgICAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwICAhIEM0MDAwMTIgMTAyNTEwMDAzNjAw',
            'AXpJU08wMjM0MDAwNzA5MjAwMzIzODg0MDEyODgxODA1MjE4MDAwMDAwMDAwMDA4MzQ4MDA1MDQxNDU5MTI1MjI2MDYwOTU5MTIwNTA0MDUwNDAxMjAyMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDA5NTkxMjAwMDBDUDAxICAgICAgICAwMjc1NDYyNzQyICAgICAgICAgICAgMDAwMDAwMDA0ODQwNDAyMDIwMjAyMDIwMjAyMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE2Q0xQR1RFUzErMDAwMDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDEyMDMhIDA0MDAwMjAgICAgICAgICAgICAgICAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwICAhIEM0MDAwMTIgMTAyNTEwMDAzNjAw',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA4MzQ4MDA1MDQxNTI0MDMzMDgyNTExMDI0MDMwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwMjQwMzkyNTEwODAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAxMjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA4MzQ4MDA1MDQxNTI0MTU5NTE1MDIxMDI0MTUwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwMjQxNTkyNTEwOTAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAxMjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDE4MzAwMDA1MDQxNTI2NDU1NTMxMzYxMDI2NDUwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTAyNjQ1OTI1MTEyMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA5MzUwMDA1MDQxNTI2NDczODc2OTUxMDI2NDcwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwMjY0NzkyNTExMzAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAxODAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AUdJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODAxMjE4MDAwMDAwMDAwMDAwODIwMDA1MDQxNTI5MTUzMzU4NTAxMDI5MTUwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwMjkxNTAwMDAwMDQ2MDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAg',
            'AUdJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODAxMjAwMDAwMDAwMDAwMDI1NDIwMDA1MDQxNTMxMDMyMzgzMjcxMDMxMDMwNTA0MDUwNDA1MDQwMTIyMTQxNTIzMTUwMDAxMjI2OTc9MjAwNTE4MDUwNDEwMzEwMzAwMDAwMDAxMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDQyNyAgMDAxICAgICAgICAgIDcgIDEgMCAg',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDAyMjMwMDA1MDQxNTMyMDg2MTU3NTYxMDMyMDgwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTAzMjA4MjA0NjA0MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDEzNjI1NTA1MDQxNTMzMDE1NDMxNDMxMDMzMDEwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTAzMzAxMjA0NjA1MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDEzNjI1NTA1MDQxNTMzNDk4OTYzMTUxMDMzNDkwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTAzMzQ5MjA0NjA2MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            'APdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjIwMDAwMDAwMDAwMDA4MzQ4MDA1MDQxNTM0MDkwODU2MjcxMDM0MDkwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTAzNDA5MjA0NjA3MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMA==',
            #'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDAzNTAwMDA1MDQxNTM1MDMwNDU4MzQxMDM1MDMwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTAzNTAzOTI1MTIyMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            #'AQNJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMzUwMDAwNTA0MTUzNTUxMDk2MTIwMDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTAzNTAzMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMDAyMDAxODA1MDQxMDM1MDMwNTA0MTAzNTAzMDAwNTA0ICAgICAgICAgIA==',
            #'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA3NjIxNTA1MDQxNTM3MTM4NzA4NjExMDM3MTMwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTAzNzEzOTI1MTI2MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            #'AQNJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNzYyMTUwNTA0MTUzODI2ODk4NDkwMDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTAzNzEzMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMDU4JiAwMDAwNDAwMDU4ISBRMTAwMDAyIDkwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMDAyMDAxODA1MDQxMDM3MTMwNTA0MTAzNzEzMDAwNTA0ICAgICAgICAgIA==',
            #'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA1MDcwMDA1MDQxNTM5MzYxMDAxMjgxMDM5MzYwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwMzkzNjkyNTEzMTAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAwNjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            #'AQFJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNTA3MDAwNTA0MTU0MDA1OTk5NTE3MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwMzkzNjAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDA1OCYgMDAwMDQwMDA1OCEgUTEwMDAwMiA5MCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAwMjAwMTgwNTA0MTAzOTM2MDUwNDEwMzkzNjAwMDUwNCAgICAgICAgICA=',
            #'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA2MTcyMDA1MDQxNTQzMjAzMzcxMTkxMDQzMjAwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTA0MzIwOTI1MTM5MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjE3MjAwNTA0MTU0MzI0MjY3OTM3MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTA0MzIwMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMDQzMjAwNTA0MTA0MzIwMDAwNTA0ICAgICAgICAgIA==',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjE3MjAwNTA0MTU0MzU1MjM0MTE4MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTA0MzIwMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMDQzMjAwNTA0MTA0MzIwMDAwNTA0ICAgICAgICAgIA==',
            #'AUdJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODAxMjE4MDAwMDAwMDAwMDA1MDkwMDA1MDQxNTQ1NDk4MTgyOTgxMDQ1NDkwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNDU0OTAwMDAwMDAxMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiAxICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgIFkgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAw',
            #'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNTA5MDAwNTA0MTU0NTU1MDk1NDc3MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNDU0OTAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDEwNDU0OTA1MDQxMDQ1NDkwMDA1MDQgICAgICAgICAg',
            #'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNTA5MDAwNTA0MTU0NjI2NDIxNTkyMDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNDU0OTAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDEwNDU0OTA1MDQxMDQ1NDkwMDA1MDQgICAgICAgICAg',
            #'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA1MDkwMDA1MDQxNTQ5NDUwMTk2MzMxMDQ5NDUwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNDk0NTkyNTE1MTAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAwNjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            #'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNTA5MDAwNTA0MTU0OTU1MzcxNTQyMDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNDk0NTAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5MCEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDEwNDk0NTA1MDQxMDQ5NDUwMDA1MDQgICAgICAgICAg',
            #'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNTA5MDAwNTA0MTU1MDI2NzgyNjU1MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNDk0NTAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDEwNDk0NTA1MDQxMDQ5NDUwMDA1MDQgICAgICAgICAg',
            #'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDA3NjEwMDA1MDQxNTUyMjAzMjUyMTgxMDUyMjAwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTA1MjIwOTI1MTUzMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNzYxMDAwNTA0MTU1MjI1NDgwNjMxMDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTA1MjIwMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMDUyMjAwNTA0MTA1MjIwMDAwNTA0ICAgICAgICAgIA==',
            #'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDA1MDkwMDA1MDQxNTUzNDgyNzA4ODQxMDUzNDgwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNTM0ODkyNTE1NTAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAwNjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNzYxMDAwNTA0MTU1MjU2MzUyMTQ0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTA1MjIwMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMDUyMjAwNTA0MTA1MjIwMDAwNTA0ICAgICAgICAgIA==',
            #'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNTA5MDAwNTA0MTU1MzU2MjYwNTI4MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNTM0ODAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5MCEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDEwNTM0ODA1MDQxMDUzNDgwMDA1MDQgICAgICAgICAg',
            #'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAwNTA5MDAwNTA0MTU1NDI3NjEwMDg3MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDEwNTM0ODAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDEwNTM0ODA1MDQxMDUzNDgwMDA1MDQgICAgICAgICAg',
            #'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDIxMjgwMDA1MDQxNTU5NDU1NTgxMjUxMDU5NDUwNTA0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTA1OTQ1OTI1MTYxMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDAwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBPICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAyMTI4MDAwNTA0MTYwMDE2NjIzNTU4MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTA1OTQ1MDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMDU5NDUwNTA0MTA1OTQ1MDAwNTA0ICAgICAgICAgIA==',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAyMTI4MDAwNTA0MTYwMDQ3MDg1MDI0MDUwNDA1MDQwMTI1OTIxNDE1MjMxNTAwMDEyMjY5Nz0yMDA1MTgwNTA0MTA1OTQ1MDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA0MjcgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMDU5NDUwNTA0MTA1OTQ1MDAwNTA0ICAgICAgICAgIA==',
            #'AcdJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODA1MjE4MDAwMDAwMDAwMDEyMDcwMDA1MDQxNjAyMjI3ODU1NTExMTAyMjIwNTA0MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTEwMjIyOTI1MTcwMDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MTM5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCAgICAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjAxMDAwMDAwMDAwMDAxNTIwMDAwMDAwMDAwNDg0MDAwMDEyNCYgMDAwMDYwMDEyNCEgUTEwMDAwMiAwMCEgUTIwMDAwMiAwOSEgQzQwMDAxMiAxMDI1MTAwMDM2MDAhIDA0MDAwMjAgICAgICAgICAgICAgWSAgICAgICAhIEMwMDAwMjYgMzQwICAwMDEgICAgICAgICAgNyAgMSAwIDA=',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAxMjA3MDAwNTA0MTYwMjUzNTU5Njk2MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTEwMjIyMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkwISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTAyMjIwNTA0MTEwMjIyMDAwNTA0ICAgICAgICAgIA==',
            #'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAxMjA3MDAwNTA0MTYwMzI0NTU4NTE1MDUwNDA1MDQwMTI1OTIxNDc3MjEzNTAwMDAwMzU4ND0yMDA1MTgwNTA0MTEwMjIyMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTAyMjIwNTA0MTEwMjIyMDAwNTA0ICAgICAgICAgIA==',
            #'AdVJU08wMjQwMDAwNzcwMjEwMzIzQTg0MDAyRTgxODA1MjE4MDAwMDAwMDAwMDExMDc1MDA1MDQxNjA1MTg4Nzg1MTgxMTA1MTgwNTA0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDExMDUxODkyNTE4MDAwMDAwMENQMDEgICAgICAgIDAyNzU0NjI3NDIgICAgICAgICAgICAwMDAwMDAwMDQ4NDEzOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMTAwMDAwMDAwMDAwMTUyMDAwMDAwMDAwMDQ4NDAwMDAxNDAmIDAwMDA3MDAxNDAhIFExMDAwMDIgMDAhIFEyMDAwMDIgMDkhIFE2MDAwMDYgMDAwNjAzISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICBZICAgICAgICEgQzAwMDAyNiAzNDAgIDAwMSAgICAgICAgICA3ICAxIDAgMA==',
            'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAxMTA3NTAwNTA0MTYwNTQ5MjYzMjU0MDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDExMDUxODAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5MCEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDExMDUxODA1MDQxMTA1MTgwMDA1MDQgICAgICAgICAg',
            'AVNJU08wMjQwMDAwNzcwNDMwQjIyMjg0MDAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAxODAwMDAwMDAwMDAxMTA3NTAwNTA0MTYwNjIwMTExNTgzMDUwNDA1MDQwMTIyMTQ3NzIxMzUwMDAwMDM1ODQ9MjAwNTE4MDUwNDExMDUxODAwMDAwMENQMDEgICAgICAgIDQ4NDAwMDE0MCYgMDAwMDcwMDE0MCEgUTEwMDAwMiA5ICEgUTIwMDAwMiAwOSEgUTYwMDAwNiAwMDA2MDMhIEM0MDAwMTIgMTAyNTEwMDAzNjAwISAwNDAwMDIwICAgICAgICAgICAgICAgICAgICAgISBDMDAwMDI2IDM0MCAgMDAxICAgICAgICAgIDcgIDEgMCAgMDIwMDE4MDUwNDExMDUxODA1MDQxMTA1MTgwMDA1MDQgICAgICAgICAg',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA1NzA1MDA1MDQxNjE0MzI0MDgyNjQxMTE0MzIwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0yMDA0MTgwNTA0MTExNDMyMDAwMDAwMDUwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA1NzA1MDA1MDQxNjE4MDQ3ODU1NzExMTE4MDQwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTExODA0MDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAzMzEwMDA1MDQxNjE4NTk1OTEzMzkxMTE4NTkwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTExODU5MDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA1NzA1MDA1MDQxNjIwMDA0ODc1MjIxMTIwMDAwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyMDAwMDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA2NDk1NTA1MDQxNjIzNDA0MDI0OTYxMTIzNDAwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyMzQwMDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjQ5NTUwNTA0MTYyMzUwMzAyNDM4MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyMzQwMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTIzNDAwNTA0MTEyMzQwMDAwNTA0ICAgICAgICAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjQ5NTUwNTA0MTYyNDAwMDI1OTU0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyMzQwMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTIzNDAwNTA0MTEyMzQwMDAwNTA0ICAgICAgICAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA4MjgwMDA1MDQxNjI3NTMyMTQ2MDIxMTI3NTMwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyNzUzMDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODI4MDAwNTA0MTYyODAwNzc0MTg4MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyNzUzMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTI3NTMwNTA0MTEyNzUzMDAwNTA0ICAgICAgICAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODI4MDAwNTA0MTYyODEwNDQ2OTM0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEyNzUzMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTI3NTMwNTA0MTEyNzUzMDAwNTA0ICAgICAgICAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAzODE4MjA1MDQxNjMxMTg2ODQxOTQxMTMxMTgwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEzMTE4MDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMzgxODIwNTA0MTYzMTQ5OTQyMjEwMDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEzMTE4MDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTMxMTgwNTA0MTEzMTE4MDAwNTA0ICAgICAgICAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMzgxODIwNTA0MTYzMjIwODYyNDUzMDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEzMTE4MDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTMxMTgwNTA0MTEzMTE4MDAwNTA0ICAgICAgICAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDE5Njg4MDA1MDQxNjMzNTIwNjIxMjAxMTMzNTIwNTA0MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEzMzUyMDAwMDAwNTQwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAxOTY4ODAwNTA0MTYzNDIzODYxMTI5MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEzMzUyMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTMzNTIwNTA0MTEzMzUyMDAwNTA0ICAgICAgICAgIA==',
            'AUVJU08wMjQwMDAwNzcwNDMwQjIyMjg0ODAyQTgwODAxMjAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAxOTY4ODAwNTA0MTYzNDU0MTUyODM5MDUwNDA1MDQwMTI1OTIxNDc2MTczOTAwMTAxMDExOT0xNzEyMTgwNTA0MTEzMzUyMDAwMDAwQ1AwMSAgICAgICAgNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA4MzAgIDAwMSAgICAgICAgICA3ICAxIDAgIDAyMDAxODA1MDQxMTMzNTIwNTA0MTEzMzUyMDAwNTA0ICAgICAgICAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAyMjc1MDA1MDQxNjM5NDU2NjY4NDQxMTM5NDUwNTA0MDUwNDA1MDQwMTI1OTIxNTQxMzMzMDA4OTAyMDAxMT0yNTEyMTgwNTA0MTEzOTQ1MDA1NjA0MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiA2MDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAzMDIwMDA1MDQxNjQxNTQxMDkyOTkxMTQxNTQwNTA0MDUwNDA1MDQwMTI1OTIxNTQxMzMzMDA4OTAyMDA3OD0yNTEyMTgwNTA0MTE0MTU0MDA1NjA1MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDAxNTYwMDA1MDQxNjQyNDI3OTI1MDQxMTQyNDIwNTA0MDUwNDA1MDQwMTI1OTIxNTQxMzMzMDA4OTAyMDA4Nj0yNTEyMTgwNTA0MTE0MjQyMDA1NjA2MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDEzMDYwMDA1MDQxNjQzNDc4Mzk5NTExMTQzNDcwNTA0MDUwNDA1MDQwMTI1OTIxNTQxMzMzMDA4OTAxMDQ4Mz0yNTEyMTgwNTA0MTE0MzQ3MDA1NjA3MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
            'ATlJU08wMjQwMDAwNzcwMjEwMzIzQTg0ODAyRTgxODAxMjAwMDAwMDAwMDAwMDA0NTEwMDA1MDQxNjQ0MzM4MDU4NzYxMTQ0MzMwNTA0MDUwNDA1MDQwMTI1OTIxNTQxMzMzMDA4OTAxMDQ0Mj0yNTEyMTgwNTA0MTE0NDMzMDA1NjA4MDAwMDAwQ1AwMSAgICAgICAgMDI3NTQ2Mjc0MiAgICAgICAgICAgIDAwMDAwMDAwNDg0MDAwMTI0JiAwMDAwNjAwMTI0ISBRMTAwMDAyIDkgISBRMjAwMDAyIDA5ISBDNDAwMDEyIDEwMjUxMDAwMzYwMCEgMDQwMDAyMCAgICAgICAgICAgICAgICAgICAgICEgQzAwMDAyNiAyMDEgIDAwMSAgICAgICAgICA3ICAxIDAgIA==',
        ];

        $respuesta = [];
        foreach($aTrx[$fecha_ymd] as $sTrx) {
            $sRespuesta = base64_decode($sTrx);
            $oInterred = new BBVAInterred();
            $aMensajeISO = $oInterred->procesaMensaje($sRespuesta);
            $respuesta[] = $aMensajeISO['iso_parsed'];
        }

        $totales = [
            'compras' => 0,
            'monto_compras' => 0,
            'cargos' => 0,
            'monto_cargos' => 0,
            'negocio' => 1,
        ];

        $aTrxs = [];
        foreach($respuesta as $res) {
            if (empty($res[39])) {
                #echo "<br>Skipped: " . print_r($res, true);
            } else if ($res[39] == '00') {
                $linea = [
                    0, //sprintf("%06s", $i++), // REGCAD-NUM-REG [6] Número consecutivo de registro
                    '3', // REGCAD-TIPO-REG [1] Tipo de registro. Fijo 3
                    substr($res[37], 0, 6), // REGCAD-FECHA [6] Fecha valor del pagare (AAMMDD)
                    '1', // REGCAD-CVE-OPERACIÓN [1] Clave de la operación del Pagaré 1= Compra On-Line (Aut.Bnmx) 2= Compra On-Line (Aut.Cadena) 3= Compra Off-Line 4= Devolución 5= Compra diferida On-Line 6= Devolución Diferida Off-Line
                    $res[38] ?? '000000', // REGCAD-AUTORIZACION [6] Número con el cual autorizó BBVA Bancomer
                    substr($res[4], 2), // REGCAD-IMPORTE [10] Monto de la transacción
                    // REGCAD-REFERENCIA [23] Número único para la localización de pagares “
                        '7455546', // [7] 7455546” = Valor Fijo.
                        substr($res[37], 1, 1), // [1] “A” = último dígito del año.
                        date("z", strtotime(substr($res[37], 0, 2) . '-' . substr($res[37], 2, 2) . '-' . substr($res[37], 4, 2))) + 1, // [3] “DDD = fecha juliana.
                        sprintf("%011s", $res[11]), // [11] “99999999999” = 11 posiciones libre numérico.
                        $this->calcLuhn($res[11]), // [1]  “1” = dígito verificador ( módulo 10)
                    sprintf("%- 19s", substr($res[35], 2, strpos($res[35], '=') - 2)), // REGCAD-TARJETA [19] Número de tarjeta (BBVA Bancomer, Visa, MC, BBVA Bancomer, Carnet, Amex)
                    '0000', // REGCAD-MOT-RECH [4] Motivo de rechazo del movimiento. Campo exclusivo para BBVA Bancomer. La interred debe enviar el valor fijo: 0000
                    '0000', // REGCAD-STAT-REG [4] Estatus del registro. La interred debe enviar el valor fijo: 0000
                    substr($res[37], 6, 6), // REGCAD-TIME [6] Hora en que se efectúo la transacción (HHMMSS)
                    '0007', // REGCAD-INDIC-COM-ELEC [4] Indicador de Comercio Electrónico: 0 = No es transacción de Comercio Electrónico 5 =Transacción electrónica segura con certificado del tarjetahabiente 6 =Transacción electrónica segura sin certificado del tarjetahabiente, con certificado del negocio 7 =Transacción de comercio electrónico sin certificados, con canal encriptado 8 = Transacción de comercio electrónico No segura
                    '01', // [2] Modo de ingreso de datos de la cuentas emisora: “00” Información desconocida “01” Información digitada “05” Información obtenida de tarjeta con chip. “07” Contactless “80” FallBack  “90” Información obtenida de la banda magnética del plástico “91” Contactless MSD (banda magnética)
                    '000000000', // [9] Cash back 7 enteros 2 decimales
                    '1', // [1] Capacidad de la terminal para lectura de datos: '1' No hay terminal (elaborado manualmente) '2' Con lectora de banda '3' Contactless  '4' Lector de caracteres ópticos '5' Lector de CHIP(circuito integrado)
                    $this->obtienePlan($res[63])['plan'], // [2] Plan a utilizarse '00' Sin plan '03' Plan sin intereses '05' Plan con intereses '07' Compre hoy pague después
                    $this->obtienePlan($res[63])['diferido'], // [2] Número de meses en que el pago no se hace exigible(Compre hoy, pague después)
                    $this->obtienePlan($res[63])['parcialidades'], // [2] Número de meses en que se van a dividir los pagos (con o sin intereses), justificado con ceros a la izquierdo.
                    '000000', // [6] Número de boleta utilizado en la transacción
                    '0000', // [4] Número de terminal donde se efectuó la transacción
                    '000', // [3] Número de tienda donde se efectuó la transacción
                ];
                if (!empty($res[38])) {
                    if (!empty($aTrxs[$res[38]])) {
                        unset($aTrxs[$res[38]]);
                        if ($res[3] == '180000' || $res[3] == '000000') {
                            $totales['compras'] -= 1;
                            $totales['monto_compras'] -= $res[4];
                        } else if ($res[3] == '200000') {
                            $totales['cargos'] -= 1;
                            $totales['monto_cargos'] -= $res[4];
                        }
                        $totales['negocio'] -= 1;
                    } else {
                        $aTrxs[$res[38]] = $linea;
                        if ($res[3] == '180000' || $res[3] == '000000') {
                            $totales['compras'] += 1;
                            $totales['monto_compras'] += $res[4];
                        } else if ($res[3] == '200000') {
                            $totales['cargos'] += 1;
                            $totales['monto_cargos'] += $res[4];
                        }
                        $totales['negocio'] += 1;
                    }
                }
            }
        }
        // Escribe registros en batch
        $registros = 0;
        $batch_linea = [];
        foreach($aTrxs as $iTrxId => $aTrnx) {
            $aTrnx[0] = sprintf("%06s", $i++); // REGCAD-NUM-REG [6] Número consecutivo de registro
            $batch_linea[] = implode('', $aTrnx) . "\n";
            #$totales['compras'] += 1;
            #$totales['monto_compras'] += $aTrx[5];
            $registros += 1;
        }

        $batch_footer_1 = [
            sprintf("%06s", $i), // [6] Número consecutivo de registro
            '4', // [1] Tipo de registro. Fijo: 4
            sprintf("%07s", $totales['compras']), // [7] Número de compras en el archivo
            sprintf("%014s", $totales['monto_compras']), // [14] Monto de las compras del archivo
            sprintf("%07s", $totales['cargos']), // TRCAD-NUM-DEB [7] Número de cargos del archivo
            sprintf("%014s", $totales['monto_cargos']), // TRCAD-IMP-DEB [14] Monto de los cargos del archivo
            sprintf("%06s", $totales['negocio']), // [6] Número de Header`s de Negocio (registros tipo 2) y de Detalle (registros tipo3)
            '000000', // [6] Hora en que BBVA Bancomer recibió el archivo  de entrada (HHMMSS). La Interred enviará el valor fijo: 000000
            '000000', // [6] Hora en que BBVA Bancomer finalizó el proceso del archivo de entrada y generó el archivo de Retorno con los rechazos (HHMMSS). La Interred enviará el valor fijo: 000000
            '                                                      ', // [54] Espacios para uso futuro
        ];

        $batch = implode('', $batch_header_1) . "\n" . implode('', $batch_header_2) . "\n" . implode('', $batch_linea) . implode('', $batch_footer_1);

        Storage::put($batch_filename, $batch);

        return $batch;

    }

    private function calcLuhn(string $sNum): int
    {
        $sChecksum = '';
        foreach (str_split(strrev($sNum . '0')) as $i => $d) {
            $sChecksum .= $i % 2 !== 0 ? $d * 2 : $d;
        }
        $iDigit = strrev((string) array_sum(str_split($sChecksum)))[0];
        $iResult = (10 - $iDigit);
        if ($iResult == 10) {
            $iResult = 0;
        }
        return $iResult;
    }

    private function obtienePlan($sCampo63): array
    {
        $aPlan = [
            'plan' => '00',
            'parcialidades' => '00',
            'diferido' => '00',
        ];
        if (!empty($sCampo63)) {
            // Obtiene data de tokens
            $sTokens = substr($sCampo63, 15);
            // Separa campo de tokens
            $aTmpTokens = explode('! ', $sTokens);
            $aTokens = [];
            foreach($aTmpTokens as $sTmpToken) {
                $aTokens[substr($sTmpToken, 0, 2)] = substr($sTmpToken, 2);
            }
            // Obtiene plan de pagos
            if (isset($aTokens['Q6'])) {
                $aPlan['plan'] = substr($aTokens['Q6'], -2, 2);
                $aPlan['parcialidades'] = substr($aTokens['Q6'], 8, 2);
                $aPlan['diferido'] = substr($aTokens['Q6'], 6, 2);
            }
        }
        return $aPlan;
    }
}
